### ISSUE TITLE
Definir linguagem de programação

### ISSUE THREAD

**Issue by Dkmister** [Dkmister/TCP_Project#1]
Gostaria de ver com vocês qual linguagem seria a mais adequada para o trabalho.
Vou colocar o exemplo de algumas com Orientação a Objetos:
- [ ] - C++ 
- [ ] - Java
- [ ] - Ruby
- [x] - Python
- [ ] - Rust
- [ ] - Swift

Pode-se sugerir mais exemplos, mas é necessário definir uma para o prosseguimento do trabalho.

**Comment by catafrato** [comment]
Conheço Python bastantinho. Java ainda não mas, pela cadeira, pretendo desenvolver um conhecimento sólido dela, ainda que ela esteja em vias de obsolescência.

**Comment by Dkmister** [comment]
Decidido em conjunto por Python
