### ISSUE TITLE
Trabalho Prático - Fase 2

### ISSUE THREAD

**Issue by Dkmister** [Dkmister/TCP_Project#10]
Etapas a serem concluídas:

- [x] **Leitura do texto**: <https://moodle.inf.ufrgs.br/pluginfile.php/106755/mod_resource/content/1/OOSC-Cap3-Modularity.pdf>
- [x] **Descrição do programa**:
a) o objetivo do programa;
b) seus elementos (módulos e classes) principais e 
os seus objetivos; Isto pode ser feito com um parágrafo 
para cada módulo/classe além dos atributos e métodos definidos até agora;
c)   se   existir   interface   com   usuário,   cópias   das   principais   
telas/janelas   e   uma   explicação
(uma frase ou 2) de cada uma.
- [x] **Avaliação de modularidade**:
Discussão e Exemplificação de como os
critérios, regras e princípios de modularidade descritos no
texto lido são aplicados.
- [x] **Discussão e solução do problema**:
Avaliação dos itens da etapa anterior a fim de chegar numa conclusão, 
ou seja solução para casos não atendidos.

**Comment by pietrodegrazia** [comment]
# Descrição do Programa

a) O programa consiste em um software que irá receber entrada de comandos do usuário através do teclado e baseado em tais entradas tocará sons com notas, volume e batidas de acordo.

b)

## Partitura

Classe que irá representar a música como um todo. Possui como atributo todo o texto que o usuário entrou para determinado arquivo. No futuro poderá possuir também uma lista ordenada de Notas e Tempos, provavelmente transformados em um objeto apenas do tipo Comando(padrão de implementação).

## Nota

Classe que irá representar as notas musicais: lá, sí, dó, etc..  Inclui a frequencia base da nota, e no futuro deverá incluir também algum atributo que auxilie nas diferentes oitavas que ela pode ter.

## Tempo

Classe ainda não foi implementada, mas achamos que será necessária para controlar o ritmo da musica.

## TrechoDeSom

Achamos que teremos de implementar uma classe que sirva como buffer para o som, algo que é comum em aplicações que lidam com áudio.

**Comment by Dkmister** [comment]
Ok, 1ª parte e 2ª parte concluída.
Estará num arquivo, vou falar com o @Catafrato para resolvermos o resto 😄
