### ISSUE TITLE
Padrões - Não sou Pythonista

### ISSUE THREAD

**Issue by pietrodegrazia** [Dkmister/TCP_Project#4]
# O Problema

Algum de vocês pode ver que q eu to fazendo errado no trabalho de padrões? 
Acho que eu to usando errado a string de Message.payload, pq não ta dando certo a função de igualdade.
# O Traceback

Traceback (most recent call last):  
  File "/Users/pietrodegrazia/Documents/Developer/Piton/main.py", line 10, in <module>  
    print(firstMsg == secondMsg)  
  File "/Users/pietrodegrazia/Documents/Developer/Piton/Message.py", line 24, in **eq**  
    print(self._payload + " " + other._payload)  
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'    
# O Erro

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by pietrodegrazia** [comment]
@Catafrato , @Dkmister

**Comment by pietrodegrazia** [comment]
Ps, o padrão que eu to implementando é o Valor Objeto, tem uma explicação já no text.md

**Comment by Dkmister** [comment]
Estou dando uma lida. 
Acho legal a gente fazer um padrão nos commits.
Tu tá comitando referente a esse issue.
Se teu commit for por exemplo "#4: Criado cobra.py e adicionado texto.txt" , além de ficar claro a qual issue tu está se referindo, o teu commit irá ligado a esse issue na mensagem.

**Comment by Dkmister** [comment]
É que tu deu print dentro do print, e esse foi o erro.
