### ISSUE TITLE
Formalismos de commits

### ISSUE THREAD

**Issue by Dkmister** [Dkmister/TCP_Project#5]
@Catafrato e @pietrodegrazia 

Estou passando esse Issue para formalizar como eu sugiro que fique melhor a organização de issues e commits.

Os issues são criados justamente para se melhor referenciar aos commits. Commits serão sempre uma referência a algum issue.

Vocês podem olhar exemplos na minha ONG, WebIWG, [https://github.com/webiwg/historia-web-pt/commits/master] . 

Exemplo:
# Numero_do_issue : O que foi feito no commit

**Comment by Dkmister** [comment]
@Catafrato e @pietrodegrazia de acordo com as regras?

**Comment by catafrato** [comment]
D'accord.
