### ISSUE TITLE
Elaboração de lista de requisitos

### ISSUE THREAD

**Issue by Dkmister** [Dkmister/TCP_Project#6]
### Definição Formal do Trabalho

**1a Parte:**

Elaborar uma lista (informal, em português) dos requisitos que o sistema deve possuir no ponto de vista dos autores do projeto. Cada requisito é um item da lista e pode ser do tipo funcional (relativo a funcionalidade do sistema)   ou   não-funcional   (relativo   a   características   de   performance,   usabilidade,   cronograma,   orçamento,limitações tecnológicas, entre outras). Neste trabalho em particular, o grupo deve elaborar uma lista de quaisoperações   o   sistema   permitirá   que   sejam  realizadas  sobre   quais   elementos,   deixando   claro   quais   as conseqüências (alteração de aparência, mensagens ao usuário, etc).

**P.S.:** Referente ao issue #3

**Comment by pietrodegrazia** [comment]
# Requisitos

### Funcional
- Abrir o programa e já poder digitar
- Pedir para salvar txt antes de rodar pela primeira vez
- Digitar comandos e rodar
- Abrir um txt 
- Salvar seu txt
- Criar novo txt

### Não Funcionais
- Deve rodar em ambientes Unix
- Deve ter a aparência do sistema operacional em uso para melhor experiência de usuário
- Não deve acarretar em custos extras fora a mão de obra
- Deve respeitar o cronograma repassado pelo professor, tendo reuniões quinzenais para evitar imprevistos e atrasos.
- Não será possível usufruir do programa sem que o computador possua uma saída de som
