### ISSUE TITLE
Projeto Funcional e Definição de Classes

### ISSUE THREAD

**Issue by Dkmister** [Dkmister/TCP_Project#7]
### Definição Formal do Trabalho

**2a Parte:**

Nesta      parte,   o   grupo   deve   **PROJETAR   A   PARTE   FUNCIONAL**      do   sistema,   preferencialmente **DEFININDO CLASSES** – com atributos e métodos -  correspondentes a Tipos Abstratos de Dados que fazem parte do programa. Se for utilizada alguma notação não vista em aula para descrever as classes, um resumo desta deve ser entregue ao professor junto com a documentação do trabalho, assim como a lista de referências bibliográficas consultadas sobre esta notação.

P.S.: Referente ao issue #3

**Comment by catafrato** [comment]
Na conversa por Hangouts às 14h30 do dia 07/10, eu e o @pietrodegrazia optamos por usar a versão 2.7.12 do Python, e a biblioteca pyaudio para o áudio. De acordo, @Dkmister?

Pyaudio: https://people.csail.mit.edu/hubert/pyaudio/

**Comment by Dkmister** [comment]
Sim

**Comment by catafrato** [comment]
Nossa classe principal é o texto, que podemos chamar, por exemplo, de **Partitura**.

Além disso, teremos buffers de som, de trechos da **Partitura** já convertidos a áudio. Portanto, creio ser necessária uma classe **TrechoDeSom**, de tamanho de dados maleável - como se fosse uma string já convertida de texto a notas.

Ao trabalhar com áudio, sempre é bom bufferizar (fazer os processamentos de conversão necessários) um trecho longo e só então tocar, para que a experiência do usuário seja a melhor possível. Recebi até a dica de um colega, que sabe muito de áudio, de que talvez fosse válido bufferizar TUDO antes de tocar.

Que tal?

**Comment by Dkmister** [comment]
A classe **Partitura** também deveria ter as subclasses **Nota** e **Tempo** . 

Além de que uma nota lá, si, mi , dó, ré, mi, fá, sol pode ter diferentes oitavas. Ter algum atributo dentro de **Nota** que seja equivalente a oitava.

Foi isso que tinha me visto em mente. Acho válido ter **Partitura**, pois é um pensamento mais alto nível a respeito de como tudo é organizado numa música.

**Comment by catafrato** [comment]
De acordo sobre a **Partitura**!

 E o **TrechoDeSom**, fica sendo algo mais técnico e baixo-nível? Porque, da forma atual, seria só um buffer para ser convertido em .wav e tocado.
